# Generated by Django 3.2.15 on 2022-08-11 10:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220811_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_dob', models.DateField()),
                ('doctor_address', models.TextField(blank=True)),
                ('doctor_contact', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{9,16}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
