# Generated by Django 3.2.15 on 2022-09-30 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20220930_1700'),
        ('users', '0007_auto_20220814_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_clinic', to='clinic.clinic'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_clinic', to='clinic.clinic'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_clinic', to='clinic.clinic'),
        ),
    ]
