# Generated by Django 3.2.15 on 2022-09-30 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220930_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_contact',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{9,16}$')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_contact',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{9,16}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_contact',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{9,16}$')]),
        ),
    ]
