# Generated by Django 3.2.15 on 2022-09-12 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_appointment_status'),
        ('encounter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='encounter_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter_appointment', to='appointment.appointment'),
        ),
    ]
