# Generated by Django 3.2.15 on 2022-09-30 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20220930_1700'),
        ('encounter', '0002_alter_encounter_encounter_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='encounter_clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter_clinic', to='clinic.clinic'),
        ),
    ]
