# Generated by Django 3.2.15 on 2022-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounter', '0003_encounter_encounter_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='encounter_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
