# Generated by Django 3.2.15 on 2022-08-22 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220814_2306'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0002_auto_20220818_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_doctor', to='users.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_patient', to='users.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
