# Generated by Django 3.2.15 on 2022-09-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20220822_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('ATTENDED', 'Attended')], max_length=15),
        ),
    ]
