# Generated by Django 3.2.15 on 2022-09-30 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20220930_1700'),
        ('appointment', '0005_appointment_appointment_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_clinic', to='clinic.clinic'),
        ),
    ]
