# Generated by Django 3.2.15 on 2022-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appointment_appointment_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
