# Generated by Django 3.2.15 on 2022-08-22 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinic_id', models.AutoField(primary_key=True, serialize=False)),
                ('clinic_name', models.CharField(max_length=255)),
                ('clinic_address', models.TextField(blank=True)),
                ('clinic_contact', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{9,16}$')])),
            ],
        ),
    ]
