# Generated by Django 3.2.15 on 2022-09-30 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='clinic_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_contact',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{9,16}$')]),
        ),
    ]
