# Generated by Django 3.2.15 on 2022-09-15 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounter', '0002_alter_encounter_encounter_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis_descr', models.TextField(blank=True, null=True)),
                ('diagnosis_prescription', models.TextField(blank=True, null=True)),
                ('diagnosis_encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_encounter', to='encounter.encounter')),
            ],
        ),
    ]
