# Generated by Django 3.2.15 on 2022-09-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_icd',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_notes',
            field=models.JSONField(default={}),
        ),
    ]
