# Generated by Django 3.2.15 on 2022-09-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_alter_diagnosis_diagnosis_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='diagnosis_notes',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_blood_pressure',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_heart_rate',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_height',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_oxy_saturation',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_resp_rate',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_temp',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_weight',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
