# Generated by Django 3.2.15 on 2022-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_auto_20220929_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_icd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
