"""Tests for the voice recognition API."""

from pprint import pprint
from django.test import TestCase
from django.urls import reverse
from rest_framework.test import APIClient
from rest_framework import status
from users.models import User

VOICE_RECOGNITION_WEB_URL = reverse("Voice Recognition Speech to Text for Web")
VOICE_RECOGNITION_MOBILE_URL = reverse(
    "Voice Recognition Speech to Text for Mobile")


def create_user(email="testuser@example.com", password="testpass123", role=User.Role.ADMIN, is_staff=True):
    """Create and return a user. Returns AdminUser by default."""
    return User.objects.create_user(email=email, password=password, role=role, is_staff=is_staff)


class PublicVoiceRecognitionAPITests(TestCase):
    """Test unauthenticated API requests."""

    def setUp(self):
        self.admin_user = create_user()
        self.client = APIClient()

    def test_auth_required(self):
        """TODO: This test does not work
        Test Auth not required for retriving VoiceRecognitions."""
        res = self.client.post(VOICE_RECOGNITION_WEB_URL)
        # self.assertEqual(res.status_code, status.HTTP_400_BAD_REQUEST)

    def test_stt_mobile(self):
        """Test Speech to Text for Mobile, using base64 encoded string as audio stream."""
        payload = {
            "data": "//FsQBlf/AD4NABIMBkICkILj2C0THv6h68bRgYk4kLZpeXROF1zxYvLo3x4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//xbEAZX/wBIjQANlYyIGiIUxfOiKAILxeXK0tFZZ6enohwjAdj2M53lGpUxImtJv5n+PjCnMi+9tjFKPpPKGzL9c9lwBp6u/2abmz/rDqn21d/lZVW6DGIiIMYyyoslHlmNZ9PYAUAZGIIMAEofUp/DyJ/OBQfpjP8Aw9vz/OJpzyS6bNobW3NPRwDRoCWj5v6KZtGmkDgC2kGy8ohKKYiAKQPn/RcACID5gAAB85jPHSoAAzgFIRFIBtAbAAAAAAAAAAAAAAAAOD/8WxAGV/8ASY0BCwkgSRYepAQQAQEggA3SCD4dru7nT+tPV44INEPeLtjY1kL/wCQOBw96cHM6sBlFcJPKUs7FHSYajtuYupoQOCMvQUwYTMwtQTVKFICk7/7qbPIVB1rMfCg+ffRAtaTHe1JUyRHEfK5KTBcTkuRT9EMH6x6TQT+fWt6dX4ut+E5M8tvCUtLnfxk5O1qwpCMn7qXk/P8Y0XW+6iolDppjOK79Yq5wzfG070lLSVd7T3TILAGsAAAAAAAAAAAAAAO//FsQBlf/AEwNCxIQnIEZm6EBCAAgCRYJ35Pt2Kz1oDyddY69oZ2kQkJ3yviCD/VVf7CuOoNMuXKxPmaVqKKo718acZG2ugKM/RJaocKg23Pqgto4golKtXTSCpGviPvglJSkKOBNjKLik7xADMDW6QMKIDFO5SacMCoFQAoE1QJikqFhcAcAASAIZc60QqxgDeUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcP/xbEAZf/wBPDQsKGJaFIwrIkN2CCEAosSli7BP5pKPmgepvlMo97ozDFLzRgDUEyh2XY5JQJMSqT+xcxTDhByMs65DkBXGBcwr3YWk7CdywCNKp3XPzZ2bxg0nxSIaZWTSx2bXFaANPeHKm611T3CIfzsf2oJlQRVikAFSik0b6qatSsIZ8wUrVuJJm2YsHYUsVisZ6dywKgF5rDoRFd5r0gADeLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//FsQBlf/AFENCQsJCFYTEQQtALAAIAFgP7TGM53rkmEmem5gDDEyo/f2nKsiD7B30xGPs50i9i8dCmK7OZfDCy8hWcAdMSYwXSENdow+22oq66uRkHZPFGwAKwuJMkZmu79hh8FR2V/aapvV66h9zH9Qq6sqWwneN1SdFCE4aG1oE0qEozBYWFb5wL5xAAiXvvLLV4SalMR8/mKp5xGm1UZAIZ5GxY8kxKg3+RqvmN/nfcUf3T9FgsANwAAAAAAAAAAAAAAAAAAcP/xbEAZX/wBPjQgKLFqBEgBFBhBXCgqgAgLADNpPCLC0Dx0MYEeLrzA8sldMcxsjozR0qXri0uV1aEpMoZmXlfPwSgw1y0x7Pxs7Mqm++6XetUpdKdOBQoT2xz01zxT6GxSqlUPXNxh6E6UpppeU49/c2U6sEgXBIv3SACC5ORKSDgHkpVssGIx6tmDKvrN6CMozV1QbMNJehCto5cOKv//t0vwfGdXhpbi4oIABvDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7/8WxAGV/8AUA0EYTxasQQFQAQQWxYaMaxJ45GKogtXo0X5rgdvdbXxiXk3aMobQMj1El6FfQdSm2QrXgfgGZxYZk5jB5ydsxtx3eR+YaWCUMYZSSC3JQt4nVWKTqWWCHJWlPqjR2S+3af0EWJaa14U4lRedr8ZzQKSsUABLan2cL+/N7+sak7LgsldMEARSALMeUSvV5uqXf+Fl1K5YJogBvGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4//FsQBlf/AE4VBgoomKEYAoGjKIAQIJV2P3arMlDY8UhaezO5iPCR37vbEGyLKGoBIY9wNSyo2omNHU5DwREwYpk7zXg0zdwQpcMPxJ4gP8y8+LnsgGVBUA2Y0OnJZqy8hCMaynI/Rovw43SrA6Fp7vKh0FzVKR74YJO28JwNcREBEIrECpS4F0GkCqi8wBMFQCAXkKJAA3kQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHP/xbEAZv/wBLp+xGUHlIPlNpSbRm4IwQANL5IbC7k+aCIqVbkACB06Bu7UiPbQ/FDIf/Oe6pBnuDjZ1/ZRWmRUxBPiLiIpQ684Fo3TRAG9O4iAO3rQBFUWvM1F0rlSnKKRXVgedUpK8CEFwgALwBGoRCESQUDKiAzbm27dXPEREZZM27du3VmzcICqVmctmcogBREZZREAYQiqV06XeXqnQAZ8e7yTgOQFF9EBBKaaWYzunz5VeEZtilNMzUzHb4JkzaPgGSds6h986w8D/8WxAGR/8AVT0BFSEMMwCJDEVYgKMCBq6285lrRMpJEqSVt/4N4wdZWxDDFBFGpjtXYMXrI1iGSpVpIboBXz1v01aqOUwrKOCFYuGLKdswZn6UXVSxsv5ArOSQMSgT2NVmXGXy/h0ngmEAyMaMI2S8TybPLs+HkyZfEJq0ZAnHt5PD2WyXCcQF5UAFNiQWAygMIi2eunwhdsiFiIJgAY5TD4YosQnEWESiYAbwwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOP/xbEAZv/wBVDQIUBIMCIMDsJlQItQRDEo8SEkUQgSqoLoXBaLHLHHnnk+1u5+aeEi/9yUvRzk44VCsdMQSI68rWZy2N2SU2SkNlIslKGRw/RJ5PvQh0PsfQORcdG+5+3vVIZrwHDwbIViSno+thWS0CupIUvUFNgLer9s6xIlWyWqd53raoNC1QtTx+j1IiOAAQeQDfU98x+fkFKAA6zR7Pt86ZkvXgb13/++fstLrz+n1fg0cOACEOtgAXiAaAnACqzhI051WrVDWAcD/8WxAGP/8AUw0JGApLYTmQWGghIOwbUgBxQoBKAgAGHpn5jPF7r/lNOQA1eh+0/9jrdNIBzYlpLW3m8beoAn/NsAHXgZut8cF+m4wK1BO+cC+cDLoYwV2sYGsFmjwdjEIg5XWh/4gdWc8ygAZgd3OmTsjb9XiIMQAwc0OEUCA2YwcaK2LqvUzCnJFyXZt3kQ5vT8E3rNtVx75UD5js7uWKhS1IRDmgAVCc9sJH72X+9YmqufsAG8AAAAAAAAAAAAAAAAAAADg//FsQBlf/AFINBTwQaIUSHu7NDDpQaovCsBV4WilSSJJITgBdb/lFAJut63/K4ouN3khbh4nnGgQhnwPDccC28jH3M1nAKb/X/CA3/1yAV8WMHo8wFSIT3UDLMAUxREbhvuBdJViaodBVqhFi9WqRRJaB21Cc+Mityqw8J9M5IGU5WjRIkySS2LNMowMlNFCyL5qVfOrCJKFCmJPKynaOsUAvUCABMEmFKF8dqbLgAG8JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgP/xbEAZf/wBVDQAVBIMEYREHQBqXVC2aLoMzYkUtFjjxwDjyEyFUf5RWjnIyFx/TwLuRhwHWJFTh1e3uJl3Q35Tgx74TKcxTteZh7b8RRQzurH7bWeexT6w0FEJgbUwjACBUQSiX4RTAQg2AAKVAASjGpUVH+0PyjthH8XP27759cWqS4dIyadVvnvgg9Wz5TzbqaUgBRIuAAulQpuVUg4bQDeMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABw//FsQBlf/AFONB1DYiCRR2sQagsXRTeAXQMgBqfqf99sgFeJ+f6HYAzn4n1/k8HRIQz1+y/d/O66ZCXDwg34RL0/5jSJ/WMKEq3COGA6rzH9UJlasItGBHT7UwlSNyAJRBQGYkbWid2n0yPQVfVsaehzWJcY047CoGDoS8FGhPUNyHWc+t/5Z8uYP78NI2tLUqgCxW64iABMhOcMEaUeLxzs3WA3ioAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcP/xbEAZX/wBTFQQ4BYJIFiBFKBB1QKDXJAUCKsWidWAA6e/p/V5dN+ta/D3tBSSVnKqx8F1V8FaMJcaPdWj2p8CNBofbbsrbshD9IViqke7WcrzsTZrARSCy4DikovFUAobUvnWl68l8j4UEvG8v8eSJ9LVXiexFHiWAmEiBUqd8EOOEGn9HfvcBQoADQnaE15GXdCOKNoI1xPfBcbi3zwss5pcSmjVjmkO8QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7/8WxAGV/8ATqebop2Mgp0NKtEQxWTZIhoZKAH5QB92df00VdaGqpsxnUo6nfA3ysM/qFMuuoXglwrhkGMbOw2/WoEKX4buH4yAAAww9sa4rbg71BIHCfCTYu8Oxk6IAwktG9LQlMZxYY0diWTZFSdLpY5JQMvubb0GzcGd/Xi5egImsEBcLhuDmAAC8XWy9blPyxxS5VLakQYwJEzTpO1fO+l76yA6CH2xk5KrIH3PlZW5ZoWh1Vq3ExG1hIPUAAFNEBcDIAAAAAc//FsQBlf/AE8n7Fh0c5Jj4lGIxdZqKRAQdAwAebu/7qtVkRw9LHPApwF/+V3a49X/kCs0p7LRD/Edcv/+qtOf3OWbrNOE2XxY1UvF9UVQCpEA+H8MAAEpugAK6nsDeyJF1KaoDRLwxVpU47LQXQMeEvUACESJ0IhvBIdSVBUBJNHAAIxENMW4PDw90BAAf4OAABr+jyFY6X8Hs36iwOxyXpJviWW7qs/rnm86Ve+kyIP+PbgfkxqTuY3gAAAAAAAAAAAAAAAAAAAcP/xbEAZf/wBUp+xW0RjVLRYeTH00Hw54qIXxW3IlLHF8x6VIjR1ywDQtAc0uN+ceuOmrZTXPbKHCuUuAcLxMbhtCxGBpRJ1rXBbEunb4I4t5vvFp2XCMwWLBVpFb3K1AsEBQU05jMMgYhORhVeN6X0Rw9D7k73Fp2uDabhNxRCKZWlR6/MvtX9lFhYoQBMWqErqQhKJOVzj4IAgIBOLzOWx+CZVVGd7/K+jrEFHBhBCAcw6yx+WjDhw9o4j3/lhiBDrlyBWWQAAAAA4//FsQBlf/AFO9AxMKAsSgoMZGk8UC8BpfbhZ2UlErV8rRWx4nLEcwoS/CMu6ZzcyMnCFYdnHkR0dnZwIv20OgwsLCzgFZv5nQTfhPVNPZ+H6eZY+WywfL1bBaP3N++zgBwUoJqBmpvCugNS4M8VRI1CUQW/YDf4hxMngf3AEuQDJyASgCWADsQZ/IItA0AADGBjAxgRAxgYwAG8fAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4P/xbEAZX/wBUDQlRlUJwUohQIhMUylHLoDpQMLBMFgAcf49IAVyP8R4IAG/xfGABj538sygH5iIJ4gEz7YBPnAWAvAEgNSIFAS0QT6ZEHUga8AWwgtzgv0//wehXZCt9Px+z9++6cWu9RDq9HtiEyUiM9fOY0LVuuLw7agmpjUcPDz58u5qzbNcfT1cqqcXorjx12YQKNajO9YQDjr+EB3vqVMJAbB6a4ed6c21Vxx437/CA3dZgA3gQAAAAAAAAAAAAAAAAAAAABz/8WxAGV/8AUo0HTYTsw1EYzwAbBA0i8VRCkoVFAC/d+BgAM5/u/88wCsI9f/0wgC54js1Z95gIoA9UA2QPpIHLAsBmAsBcDKBmgDKBmgCYEuEE+0Bm7Pe4QICAPhU4sZqKgq1/XjomSCKIKIp75anETAVEAfakQyIyIBE3JVFNpoT9Xf1XeGlp1rHs66nNIEo7daAFs8iAZcYM3ISG956Nat3/sOHlQwN908oTAG8LAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOA//FsQBlf/AFMNAyQEwwQhAEhjFAkMRn2dVVwWqOCxyJXIAtEwhCICyA//W4R4dVueV7Vsc/PpMyi6mpqTOUtvBU42x/T+VsJJo7kvcvf0JXwb4Ctzmf3hEXek4l8eXzQoSVHtquijejCIlAQVKFRYBQuAQDBQDLAS8Xk+0WWmqtKmomjtEk04K8TOgDNkGdx9MOcueEP1/EGWOLQ77vrOcx8izgJgwgJlmKMExzSVpEABvCAAAAAAAAAAAAAAAAAAAAAAAAAAAAADv/xbEAZf/wBRjQUjGJI1CrhIABQQCAtE6j+B2++5hdi/r+nYhWc67pHdAcDZHwkF4kUDpofAYdSG0AAejdQg7UAEqzxT1vJcKB4isBP1KjeENPgIwhdrnejMXjdb1y1z37HoyYdP01q+DBJXLBKCJMAYLVEVaSBklT10y4/55FI6r5EsnkTP4vR/GJXyOkqlHk6MOR4cvMmwDyVSyARCUABFCXXEVx2s9EQAA3h4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAc//FsQBlf/AE+NCBosyDZBLgKGBBdAQQGw1CM+VuAXFGMurEmXTL7/TPwj+QJfc9L89EfCRlLEdH4PSt97IUXyW5EHKXJm09El9Ru5sloIzlUlsc801mSFVqQIJhK0NC0E2oVqglyAR1BnFfImPFIUmEpXM2Nw5qYVmxHUsK9/vrviHSKMpVnZJC421nQxCy5kUawbgraaFwlFIIrkoJgDeNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHP/xbEAZX/wBPDQYqFJoxQLAAACAhAjV4QYMfpnbb5mprYbpBZ2d1ZmyA7GZ7F1rlRSPlM5QgzviQZLET/7VoQxLFSsalzQXoqibx+48kYLTagBfSggtC3bpagtCqFoVoWWvde4kuE7Be+h5Ea9pbBTyWtc8m39u0hW1ma8EUGjshJZYF4RizIFdETMXCzEF6EHAITC+xTJOckp28Sk7LzABvGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4D/8WxAGV/8ATw0GIVBggVwAAAIoWNA6Ic6Tb0dAe3sR5NRJSQvOjgWBqQeL/Pcv1DfSEalI6hbz1X3/234mR9DUcFFs5twBCF6a8H796c9AsKtnfNcaMIXd1hVq1qJaLVWiGvcgoibbJHJy/XH328YWlWN9ehL0uu2QbdiJGRWCRRFMXBOWwkqPF7F+a4vYTLyDGxxUSrHKEhcs/vYmNoAbxkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg//FsQBlf/AE6NBDlEYILAAAAggBsv8XjWuaP0T+0vNkbWB7dWxwVtSonZK5uMgWTDfLaS2itcPl/95H58TMvEk1jE47T3VV+JiB2HGalvfd1yoDOKkPiRLtpvdSLlArHZWMqTa5iaF4rV91IZrcId9/xjJhcc8U6sFtCZT8l3XgrjNN2+3dgTW00688xWNJlaJTqpycbRW+SCtkgqK95KFZWZ6zNM2QJqgDeHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwP/xbEAZf/wBPjQRJZEzQZwAAABASD/UkDgeA0GVzZNHdoWgF21pitHbPPxt1HfTDogLBnLnjHsfvOY5nwjpbvpTU8E3iiMXPDn3nROBtvx9mDld0gLofcODmUgjnCwd451GEtJAjhpBjHSpsgDVS9aRPCkMfDYQwJPUJT9vnChhqpsCgDPSDyLEP9V7ZqUg2XGgRtJcnM/eqZBHOzRomFBAQpsJ7l0J7KrgAbw8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOA"
        }
        expected_output = {
            "data": {
                "text": "to day is saturday",
                "words": 4
            }
        }
        res = self.client.post(VOICE_RECOGNITION_MOBILE_URL, payload)
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        self.assertEqual(res.data, expected_output)


class PrivateVoiceRecognitionAPITests(TestCase):
    """Test authenticated API requests."""

    def setUp(self):
        self.user = create_user()
        self.client = APIClient()
        self.client.force_authenticate(self.user)

    def test_voice_recognition_wav_file_upload(self):
        """
        TODO: This Test doesn't work. Need to find a way to attach custom header to the request.
        Test uploading wave file is successful."""
        file_path = "voice_recognition/tests/media/polite2.wav"
        payload = {
            "file": open(file_path, 'rb')
        }
        CONTENT_DISPOSITION = "Content-Disposition"
        self.client.credentials(
            CONTENT_DISPOSITION="attachment; filename='sound.wav'")
        res = self.client.post(VOICE_RECOGNITION_WEB_URL,
                               payload, content_type="audio/wave")
        # self.assertEqual(res.status_code, status.HTTP_200_OK)
